site_name: "CS010 SI: Fall 2017"
pages:
    - [index.md, "Home"]
    - [dis01.md, "Discussion 1: Intro to iostream Library"]
    - [lab01.md, "Lab 1: Input and Output"]
    - [dis02.md, "Discussion 2: Variables and Math"]
    - [lab02.md, "Lab 2: Variables and Math"]
    #- [lab02-solution.md, "Lab 2: Variables and Math - Solutions"]
    - [dis03.md, "Discussion 3: Characters and Branches"]
    - [lab03.md, "Lab 3: Characters and Branches"]
    #- [dis04.md, "Discussion 4: Strings and Loops"]
    #- [lab04.md, "Lab Week 4: Strings and loops"]
    #- [dis05.md, "Discussion 5: Nested Loops and Do-While"]
    #- [lab05.md, "Lab Week 5: Mock Midterm"]
    #- [dis06.md, "Discussion 6: Midterm Preparation"]
    #- [lab06.md, "Lab Week 6: Randomness"]
    #- [dis07.md, "Discussion 7: Functions"]
    #- [lab07.md, "Lab Week 7: Functions"]
    #- [dis08.md, "Discussion 8: Reference parameters"]
    #- [lab08.md, "Lab Week 8: Reference parameters"]
    #- [dis09.md, "Discussion 9: Arrays and Vectors"]
    #- [lab09.md, "Lab Week 9: Arrays and Vectors"]
    #- [dis10.md, "Discussion 10: Open Questions"]
    #- [lab10.md, "Lab Week 10: Mock Final"]
theme: readthedocs
